default: &default
  adapter: postgresql
  pool: 5
  encoding: unicode

development:
  <<: *default
  database: askme

test:
  <<: *default
  database: askme_test

production:
  <<: *default
  database: askme_prod
